language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk6
env:
  global:
  - secure: xEY3PH/G5UZ3i/EH7+CeGJBtb3CQpXrmAGxugjxUSz95k4+oD0Pz3Z53DaVr9B77XAV/A+v9vTR2p5pDvvES7nD6yyYAizNP0DAdRHcJkJvHAIcm3rMsQA54seA6POXO4hUcQlJhP7ycK+beVhSHMU0UBysBd+JSKDZWLFVj8thS6RrVxIaEwOrGL6Mf2+9iC7CoeaGOnfgLr1vZCrBZgsU8OLuqGqEkvpaD30HYGN9pn57ZXRFN7Qh/lbQiQ4L+lbPqBLkrVz0YruZr7xbzV1E8hHg2/1AaDNvMSaTi4uKpVJDw1YX/TPPRdV682HXMeM4PGkaDhhXHs9uCJBHkrHHbdKDJK4YoXsbUiO6J53O91YgrpSkxsoiTkQQkeU5CCgGWFLogC93Fk/i8CVAYWqExn9X/keVxvEoQul3T0RsfNnRiAA/O0DkDC5gmh+p5TN19CVoYFqoUdMwkVO+S1oh8t3ifXbHBbh8X3xlmxEtO+5b+xGw2s/aiPAHxU4XttoZf/xtgm+SPyvqHjh7V9z7GMpVuYR9YW80s0ujeyJ3+rk26zgdVJsf+DC5UMYv0B5PBI1GkVNKI+5IWTfHCvQeFc7brHOfeGhHyKLZpuEgV5mHmxfsro61mvrZqnmg+ei3i6UKAfZg99M/orAYXugX/e6LolJXxN8caWZaEJq4=
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
after_success:
- .utility/push-output-to-ghpages.sh